# Generated by Django 5.2.5 on 2025-09-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GurukulamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageActivites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=70)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='activites_image')),
            ],
        ),
    ]
