# Generated by Django 5.1.7 on 2025-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GurukulamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GurukulamActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='gurukulam_activities')),
                ('des', models.TextField()),
            ],
        ),
    ]
