# Generated by Django 5.2.5 on 2025-09-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GurukulamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdrishtyActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdrishyaActImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='adrishya/activities')),
                ('adrishya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adrishyaactivities_images', to='GurukulamApp.adrishtyactivities')),
            ],
        ),
    ]
