# Generated by Django 5.1.7 on 2025-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GurukulamApp', '0002_gurukulamactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='GurukulamGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images_gurukulam_gallery')),
                ('date', models.DateField()),
            ],
        ),
    ]
