# Generated by Django 5.2.5 on 2025-09-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GurukulamApp', '0002_gurukulamactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdrishyaGalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AdrishyaGallery')),
                ('date', models.DateField()),
            ],
        ),
    ]
